import { Song, Artist, Genre } from "@/types";

export const DEMO_ARTISTS: Artist[] = [
  { id: "d-artist-1", name: "The Wanderers", bio: null, image_url: null, created_at: "" },
  { id: "d-artist-2", name: "Neon Dreams", bio: null, image_url: null, created_at: "" },
  { id: "d-artist-3", name: "Pacific Shore", bio: null, image_url: null, created_at: "" },
  { id: "d-artist-4", name: "City Lights", bio: null, image_url: null, created_at: "" },
  { id: "d-artist-5", name: "Echo Valley", bio: null, image_url: null, created_at: "" },
  { id: "d-artist-6", name: "Midnight Jazz", bio: null, image_url: null, created_at: "" },
  { id: "d-artist-7", name: "Solar Wind", bio: null, image_url: null, created_at: "" },
  { id: "d-artist-8", name: "Aurora Beat", bio: null, image_url: null, created_at: "" },
];

export const DEMO_GENRES: Genre[] = [
  { id: "d-genre-1", name: "Electronic", slug: "electronic", image_url: null, created_at: "" },
  { id: "d-genre-2", name: "Pop", slug: "pop", image_url: null, created_at: "" },
  { id: "d-genre-3", name: "Hip-Hop", slug: "hip-hop", image_url: null, created_at: "" },
  { id: "d-genre-4", name: "Rock", slug: "rock", image_url: null, created_at: "" },
  { id: "d-genre-5", name: "Jazz", slug: "jazz", image_url: null, created_at: "" },
  { id: "d-genre-6", name: "Classical", slug: "classical", image_url: null, created_at: "" },
  { id: "d-genre-7", name: "R&B", slug: "rnb", image_url: null, created_at: "" },
  { id: "d-genre-8", name: "Ambient", slug: "ambient", image_url: null, created_at: "" },
  { id: "d-genre-9", name: "Folk", slug: "folk", image_url: null, created_at: "" },
  { id: "d-genre-10", name: "Dance", slug: "dance", image_url: null, created_at: "" },
];

export const DEMO_SONGS: Song[] = [
  {
    id: "d-song-1",
    title: "Sonic Horizon",
    artist_id: "d-artist-1",
    genre_id: "d-genre-1",
    duration: 232,
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    cover_url: null,
    created_at: "",
    artist: DEMO_ARTISTS[0],
    genre: DEMO_GENRES[0],
  },
  {
    id: "d-song-2",
    title: "Neon Pulse",
    artist_id: "d-artist-2",
    genre_id: "d-genre-2",
    duration: 217,
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    cover_url: null,
    created_at: "",
    artist: DEMO_ARTISTS[1],
    genre: DEMO_GENRES[1],
  },
  {
    id: "d-song-3",
    title: "Ocean Drive",
    artist_id: "d-artist-3",
    genre_id: "d-genre-3",
    duration: 198,
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    cover_url: null,
    created_at: "",
    artist: DEMO_ARTISTS[2],
    genre: DEMO_GENRES[2],
  },
  {
    id: "d-song-4",
    title: "City After Dark",
    artist_id: "d-artist-4",
    genre_id: "d-genre-4",
    duration: 254,
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    cover_url: null,
    created_at: "",
    artist: DEMO_ARTISTS[3],
    genre: DEMO_GENRES[3],
  },
  {
    id: "d-song-5",
    title: "Mountain Echo",
    artist_id: "d-artist-5",
    genre_id: "d-genre-5",
    duration: 183,
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    cover_url: null,
    created_at: "",
    artist: DEMO_ARTISTS[4],
    genre: DEMO_GENRES[4],
  },
  {
    id: "d-song-6",
    title: "Midnight Sessions",
    artist_id: "d-artist-6",
    genre_id: "d-genre-6",
    duration: 267,
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    cover_url: null,
    created_at: "",
    artist: DEMO_ARTISTS[5],
    genre: DEMO_GENRES[5],
  },
  {
    id: "d-song-7",
    title: "Solar Flare",
    artist_id: "d-artist-7",
    genre_id: "d-genre-1",
    duration: 209,
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    cover_url: null,
    created_at: "",
    artist: DEMO_ARTISTS[6],
    genre: DEMO_GENRES[0],
  },
  {
    id: "d-song-8",
    title: "Aurora Beat",
    artist_id: "d-artist-8",
    genre_id: "d-genre-7",
    duration: 241,
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    cover_url: null,
    created_at: "",
    artist: DEMO_ARTISTS[7],
    genre: DEMO_GENRES[6],
  },
];
